/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M9
 * Generated at: 2017-04-12 17:10:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import pers.qiqcheng.bookstore.bean.BookBean;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("pers.qiqcheng.bookstore.bean.BookBean");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>BookStore</title>\r\n");
      out.write("<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link href=\"css/head.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<script src=\"js/jquery-3.1.1.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"js/bootstrap.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background-color: #f4f4f4\">\r\n");
      out.write("\t<!--导航栏 -->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "head.jsp", out, false);
      out.write("\r\n");
      out.write("\t<!-- 搜索框 -->\r\n");
      out.write("\t<div class=\"col-lg-3\"></div>\r\n");
      out.write("\t<div class=\"col-lg-5\">\r\n");
      out.write("\t\t<form action=\"searchBook\">\r\n");
      out.write("\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t<div class=\"input-group-btn\">\r\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-default dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\t\tdata-toggle=\"dropdown\" type=\"button\" style=\"height: 45px;\">\r\n");
      out.write("\t\t\t\t\t\t请选择<span class=\"caret\"></span>\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">宝贝</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">店铺</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"输入关键字|书名或者作者名\"\r\n");
      out.write("\t\t\t\t\tstyle=\"height: 45px; width: 450px;\" name=\"key\" /> <span\r\n");
      out.write("\t\t\t\t\tclass=\"input-group-btn\"> <input type=\"submit\" value=\"查询\"\r\n");
      out.write("\t\t\t\t\tclass=\"btn btn-primary\" style=\"height: 45px; width: 70px;\">\r\n");
      out.write("\t\t\t\t</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"col-lg-3\"></div>\r\n");
      out.write("\t<div class=\"col-lg-12\">&nbsp;</div>\r\n");
      out.write("\t<!--轮播图-->\r\n");
      out.write("\t<div class=\"col-lg-12\" align=\"center\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-lg-1\"></div>\r\n");
      out.write("\t\t\t<div class=\"col-lg-10\">\r\n");
      out.write("\t\t\t\t<div class=\"carousel\" id=\"carouselcontainer\" data-ride=\"carousel\"\r\n");
      out.write("\t\t\t\t\tstyle=\"width: 100%; height: 390px;\">\r\n");
      out.write("\t\t\t\t\t<ol class=\"carousel-indicators\">\r\n");
      out.write("\t\t\t\t\t\t<li class=\"active\" data-target=\"#carouselcontainer\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-slide-to=\"0\">0</li>\r\n");
      out.write("\t\t\t\t\t\t<li data-target=\"#carouselcontainer\" data-slide-to=\"1\">1</li>\r\n");
      out.write("\t\t\t\t\t\t<li data-target=\"#carouselcontainer\" data-slide-to=\"2\">2</li>\r\n");
      out.write("\t\t\t\t\t\t<li data-target=\"#carouselcontainer\" data-slide-to=\"3\">3</li>\r\n");
      out.write("\t\t\t\t\t</ol>\r\n");
      out.write("\t\t\t\t\t<div class=\"carousel-inner\" style=\"width: 100%; height: 380px;\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item active\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\"><img src=\"img/headImg.jpg\" alt=\"\"></a>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"carousel-caption fontcolor\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h3>BookStore</h3>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\"><img src=\"img/headImg2.jpg\" alt=\"\"></a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\"><img src=\"img/headImg.jpg\" alt=\"\"></a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\"><img src=\"img/headImg2.jpg\" alt=\"\"></a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<a class=\"left carousel-control\" href=\"#carouselcontainer\"\r\n");
      out.write("\t\t\t\t\t\tdata-slide=\"prev\"> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"glyphicon glyphicon-chevron-left\"></span>\r\n");
      out.write("\t\t\t\t\t</a> <a class=\"right carousel-control\" href=\"#carouselcontainer\"\r\n");
      out.write("\t\t\t\t\t\tdata-slide=\"next\"> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"glyphicon glyphicon-chevron-right\"></span>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col-lg-1\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!--商品显示-->\r\n");
      out.write("\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-12\">&nbsp;</div>\r\n");
      out.write("\t\t\t\t<!--商品-->\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t\t\t<!--  style=\"color: white\" -->\r\n");
      out.write("\t\t\t\t\t");

						String flag = request.getParameter("flag");
						if (flag == null) {
							if (session.getAttribute("books") == null) {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t没有商品，敬请期待\r\n");
      out.write("\t\t\t\t\t\t<h3>\r\n");
      out.write("\t\t\t\t\t\t\t");

								} else {
										List<BookBean> books = (List<BookBean>) session.getAttribute("books");
										BookBean book = null;
										for (int i = 0; i < books.size(); i++) {
											book = books.get(i);
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-lg-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"thumbnail\"> <img\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"img/");
      out.print(book.getIsbn());
      out.write(".jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"fontcolor\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3>");
      out.print(book.getBookName());
      out.write("</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t定价: ￥");
      out.print(book.getPrice());
      out.write("元 | 库存：");
      out.print(book.getInventory());
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t出版社名称:\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      out.print(book.getPress());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t| 作者:\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      out.print(book.getAuthor());
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-xs btn-primary\">购买</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-xs btn-primary\">加入购物车</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
									}
								} else {
									List<BookBean> searchBooks = (List<BookBean>) session.getAttribute("searchBooks");
									BookBean searchBook = null;
									for (int i = 0; i < searchBooks.size(); i++) {
										searchBook = searchBooks.get(i);
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-lg-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\" class=\"thumbnail\"> <img\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsrc=\"img/");
      out.print(searchBook.getIsbn());
      out.write(".jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"fontcolor\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h3>");
      out.print(searchBook.getBookName());
      out.write("</h3>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t定价: ￥");
      out.print(searchBook.getPrice());
      out.write("元 | 库存：");
      out.print(searchBook.getInventory());
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t出版社名称:\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      out.print(searchBook.getPress());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t| 作者:\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      out.print(searchBook.getAuthor());
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-xs btn-primary\">购买</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-xs btn-primary\">加入购物车</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t");

								}
								}
							
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div>&nbsp;</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"foot col-lg-12\"  style=\"position: fixed; bottom: 0px;\">\r\n");
      out.write("    Copyright ©2017, 程祺004 All rights reserved.\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
